project:
  type: website

website:
  title: "Jared Adam"
  navbar:
    background: "#DF536B"
    pinned: true 
    left:
      - href: about.qmd
        text: Home
      - text: "CV"
        href: Jared.Adam.CV.pdf
    right: 
      - icon: github
        href: https://github.com/Jared-Adam-PSU
      - icon: linkedin
        href: https://www.linkedin.com/in/jared-adam-24b107241/
format:
  html:
   theme: cosmo
      #light: [cosmo, format/_fonts.scss, format/_light.scss, format/_button.scss]
      #dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_button.scss]
    #css: styles.css
    #toc: true



