project:
  type: website
  output-dir: _site

website:
  title: "Jared Adam"
  navbar:
    background: "#d8bfd8"
    pinned: true 
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: Jared.Adam.CV.pdf
      - text: Teaching Philosophy
        href: teaching.qmd
      - text: 'Presentation example'
        href: files/EasternESA.pdf
      - text: 'Masters defense recording'
        href: https://psu.mediaspace.kaltura.com/media/Jared+Adam%27s+Personal+Meeting+Room/1_6c58r3jx
    right: 
      - icon: github
        href: https://github.com/Jared-Adam-PSU
      - icon: linkedin
        href: https://www.linkedin.com/in/jared-adam-24b107241/
  page-footer:
      "Copyright 2023, Jared Adam. Made with[Quarto](https://quarto.org)"
format:
  html:
   theme: [cosmo, _light.scss]
      #light: [cosmo, format/_fonts.scss, format/_light.scss, format/_button.scss]
      #dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_button.scss]
    #css: styles.css
    #toc: true



