on:
  workflow_dispatch:
  push:
    # Run workflow when changes made to main branch on remote e.g., push, pull request, direct change in GH
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    # Set up virtual machine on GitHub to run workflow
    runs-on: ubuntu-latest
    permissions:
      # Need write permissions to generate pages for website
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
