on:
  workflow_dispatch:
  push:
    # Run workflow when changes made to main branch on remote e.g., push, pull request, direct change in GH
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    # Set up virtual machine on GitHub to run workflow
    runs-on: ubuntu-latest
    permissions:
      # Need write permissions to generate pages for website
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: wesbite
          directory: '_site'
